In [1]:
def mean(arr):
    s=0
    n=len(arr)
    for i in arr:
        s=s+i
        return s/n
    
    

In [2]:
mean([1,2,3,4])

0.25

In [3]:
mean([1,2,5,3,4])

0.2

In [11]:
import statistics
a=[9,2,5,4,12,7,8,11,9,3,7,4,12,5,4,10,9,6,9,4]
x=statistics.mean(a)
print(x)
y=statistics.median(a)
print(y)
z=statistics.mode(a)
print(z)

7
7.0
9


In [8]:
def stdvar(arr):
    mea=mean(arr)
    n=len(arr)
    sd=0
    r=0
    for i in arr:
        sd=sd+(i-mea)**2
        r=(sd/n)**(1/2)
        v=sd/n
        return r,v
    

In [9]:
stdvar([10,20,30])

(3.8490017945975046, 14.814814814814811)

In [20]:
import statistics
b=[9,2,5,4,12,7,8,11,9,3,7,4,12,5,4,10,9,6,9,4]
m=statistics.mean(b)
print(m)

7


In [18]:
def median(arr):
    arr.sort()
    n=len(arr)
    if n%2!=0:
        return arr[n/2]
    else:
        return arr[n/2-1]
    med = median[1,2,3,4,5]

In [21]:
        print(med)

NameError: name 'med' is not defined

In [23]:
import sklearn as sk

In [32]:
def normalization(arr):
    xmin=0
    xmax=1
    for i in arr:
        res = res + i - xmin / xmax - xmin
        return res
        

In [33]:
normalization([1,2,3,4,5])

UnboundLocalError: local variable 'res' referenced before assignment

In [5]:
import numpy as np
n=int(input("enter n"))
array=[None]*n ;
for i in range(n):
    num=int(input("Enter the no."))
    array[i]=num
print(array)

min=array[0]
max=array[0]
for i in range(1,n):
    if(min>array[i]):
        min=array[i]
    if(max<array[i]):
        max=array[i]
print("Minimum no.",min)
print("Maximum No.",max)
for i in range(n):
    x=(array[i]-min)/(max-min)
    print(i+1," normalization value is ", x)
    


enter n4
Enter the no.1
Enter the no.6
Enter the no.7
Enter the no.8
[1, 6, 7, 8]
Minimum no. 1
Maximum No. 8
1  normalization value is  0.0
2  normalization value is  0.7142857142857143
3  normalization value is  0.8571428571428571
4  normalization value is  1.0


In [7]:
import pandas as pd
import numpy as np 
df = pd.read_csv(sample.csv)

NameError: name 'sample' is not defined

In [12]:
import pandas as pd
import numpy as np 
df=pd.read_csv('sample.csv')
df


x1   x2
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.1  3.8
9  6.0  3.0

In [14]:
df['x1'].values


array([5.9, 4.6, 6.2, 4.7, 5.5, 5. , 4.9, 6.7, 5.1, 6. ])

In [15]:
df['x2'].values

array([3.2, 2.9, 2.8, 3.2, 4.2, 3. , 3.1, 3.1, 3.8, 3. ])

In [17]:
x1=df['x1'].values
x2=df['x2'].values

In [18]:
x=np.array(list(zip(x1,x2)))

In [19]:
x


array([[5.9, 3.2],
       [4.6, 2.9],
       [6.2, 2.8],
       [4.7, 3.2],
       [5.5, 4.2],
       [5. , 3. ],
       [4.9, 3.1],
       [6.7, 3.1],
       [5.1, 3.8],
       [6. , 3. ]])

In [22]:
C_x=[6.2,6.6,6.5]
C_y=[3.2,3.7,3.0]
Centroid=np.array(list(zip(C_x,C_y)))

In [21]:
Centroid



array([[5.9, 3.2],
       [4.6, 2.9],
       [6.2, 2.8],
       [4.7, 3.2],
       [5.5, 4.2],
       [5. , 3. ],
       [4.9, 3.1],
       [6.7, 3.1],
       [5.1, 3.8],
       [6. , 3. ]])

In [23]:
Centroid

array([[6.2, 3.2],
       [6.6, 3.7],
       [6.5, 3. ]])

In [31]:
import math 
for i in x:
    for j in Centroid:
        dist = np.sqrt(np.sum(np.square(i-j)))
        print(dist)
        
        
        
        


0.2999999999999998
0.8602325267042621
0.6324555320336757
1.6278820596099712
2.154065922853802
1.902629759044045
0.40000000000000036
0.9848857801796106
0.3605551275463989
1.5
1.9646882704388495
1.8110770276274832
1.2206555615733703
1.2083045973594568
1.562049935181331
1.216552506059644
1.7464249196572978
1.5
1.3038404810405295
1.802775637731994
1.6031219541881394
0.5099019513592785
0.6082762530298221
0.22360679774997916
1.2529964086141672
1.5033296378372907
1.61245154965971
0.2828427124746193
0.9219544457292886
0.5


In [37]:

    Centroid = np.array(list(zip(C_x, C_y)), dtype=np.float32)
    print("Initial Centroids")
    print(Centroid.shape)

    Centroid_old = np.zeros(Centroid.shape)
    print(Centroid_old)
    # Cluster Lables(0, 1, 2)
    clusters = np.zeros(len(x))
    print(clusters)
    error = euclidean(Centroid, Centroid_old, None)
    print(error)
    iterr = 0
    # Loop will run till the error becomes zero
    while error != 0:
        # Assigning each value to its closest cluster
        iterr = iterr + 1
        for i in range(len(x)):
            #print(X[i])
            distances = euclidean(x[i], Centroid)
            #print(distances)
            cluster = np.argmin(distances)
            clusters[i] = cluster

        Centroid_old = deepcopy(Centroid)
        
        # Finding the new centroids by taking the Mean
        for p in range(k):
            points = [x[j] for j in range(len(x)) if clusters[j] == p]
            Centroid[p] = np.mean(points, axis=0)
        print(" Centre of the clusters after ", iterr," Iteration \n", Centroid)
        error = euclidean(Centroid, Centroid_old, None)
        print("Error  ... ",error)  
    




Initial Centroids
(3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
12.537144692236463


NameError: name 'k' is not defined