In [87]:
import numpy as np
import pandas as pd


df  =  pd.read_csv('zoo.data')
    
        
        
        
        

        
    

In [88]:
df

hair  feathers   eggs  milk  airborne  aquatic  predator  toothed  \
0       1          0     0     1         0        0         1        1   
1       1          0     0     1         0        0         0        1   
2       0          0     1     0         0        1         1        1   
3       1          0     0     1         0        0         1        1   
4       1          0     0     1         0        0         1        1   
..    ...        ...   ...   ...       ...      ...       ...      ...   
96      1          0     0     1         0        0         0        1   
97      1          0     1     0         1        0         0        0   
98      1          0     0     1         0        0         1        1   
99      0          0     1     0         0        0         0        0   
100     0          1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  type  
0           1         1         0     0     4     0         0        1     1  
1           1         1         0     0     4     1         0        1     1  
2           1         0         0     1     0     1         0        0     4  
3           1         1         0     0     4     0         0        1     1  
4           1         1         0     0     4     1         0        1     1  
..        ...       ...       ...   ...   ...   ...       ...      ...   ...  
96          1         1         0     0     2     1         0        1     1  
97          0         1         1     0     6     0         0        0     6  
98          1         1         0     0     4     1         0        1     1  
99          0         1         0     0     0     0         0        0     7  
100         1         1         0     0     2     1         0        0     2  

[101 rows x 17 columns]

In [89]:
df.head()


hair  feathers   eggs  milk  airborne  aquatic  predator  toothed  \
0     1          0     0     1         0        0         1        1   
1     1          0     0     1         0        0         0        1   
2     0          0     1     0         0        1         1        1   
3     1          0     0     1         0        0         1        1   
4     1          0     0     1         0        0         1        1   

   backbone  breathes  venomous  fins  legs  tail  domestic  catsize  type  
0         1         1         0     0     4     0         0        1     1  
1         1         1         0     0     4     1         0        1     1  
2         1         0         0     1     0     1         0        0     4  
3         1         1         0     0     4     0         0        1     1  
4         1         1         0     0     4     1         0        1     1

In [90]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import metrics


In [91]:
X = df.values[:, 0:16]
Y = df.values[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3)
 




In [92]:
X

array([[1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 0, 0]])

In [93]:
Y

array([1, 1, 4, 1, 1, 1, 1, 4, 4, 1, 1, 2, 4, 7, 7, 7, 2, 1, 4, 1, 2, 2,
       1, 2, 6, 5, 5, 1, 1, 1, 6, 1, 1, 2, 4, 1, 1, 2, 4, 6, 6, 2, 6, 2,
       1, 1, 7, 1, 1, 1, 1, 6, 5, 7, 1, 1, 2, 2, 2, 2, 4, 4, 3, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 7, 4, 1, 1, 3, 7, 2, 2, 3, 7, 4, 2, 1, 7, 4, 2,
       6, 5, 3, 3, 4, 1, 1, 2, 1, 6, 1, 7, 2])

In [94]:
clf=DecisionTreeClassifier(criterion='entropy')

In [95]:
X_train

array([[0, 0, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 1, 1],
       [0, 1, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 1]])

In [96]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [97]:
pred=clf.predict(X_test)

In [98]:
pred

array([7, 3, 4, 2, 4, 1, 4, 1, 2, 1, 2, 1, 6, 7, 1, 7, 1, 4, 1, 2, 1, 2,
       5, 6, 2, 4, 6, 1, 1, 1, 1])

In [99]:
y_test

array([7, 3, 4, 2, 4, 1, 4, 1, 2, 1, 2, 1, 6, 7, 1, 7, 1, 4, 1, 2, 1, 2,
       5, 6, 2, 4, 6, 1, 1, 1, 1])

In [100]:
print(accuracy_score(y_test,pred))

1.0


In [101]:
print(confusion_matrix(y_test,pred))

[[12  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0]
 [ 0  0  1  0  0  0  0]
 [ 0  0  0  5  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0  3  0]
 [ 0  0  0  0  0  0  3]]


In [103]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00         6
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         5
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         3
           7       1.00      1.00      1.00         3

    accuracy                           1.00        31
   macro avg       1.00      1.00      1.00        31
weighted avg       1.00      1.00      1.00        31

